### ISSUE TITLE
go: jsonformat package is not go gettable 

### ISSUE THREAD

**Issue by sam-virta** [google/fhir#18] opened 2020-07-16 02:49 UTC
Currently the imports in the jsonformat go package require consumers to also be using bazel. It would be nice if this implementation was directly consumable (as in, via go modules)

If you aren't planning on supporting this, please let me as we will try a go mod hack or begrudgingly maintain a fork 🙂

**Comment by nickgeorge** [comment] 2020-07-17 20:29
Great idea.  We have a maven jar for Java, and will have pypi support for Python, so it makes sense to also support go modules.  We'll investigate making this coexist with bazel - as long as that plays nicely we should be able to get this out soon.

**Comment by andyblum** [comment] 2020-07-30 01:50
I want to emphasize what @sam-virta stated.  I am trying to use your code to convert FHIR JSON to proto.  It is very frustrating as every road leads through Bazel.   Despite having plugins I have had a hard time getting Bazel IDE support to work in either Eclipse or IntelliJ.   Very frustrated.  I am going to just copy and paste code which is a hack.

**Comment by nikklassen** [comment] 2020-07-30 16:16
This is a high priority for us given the feedback from this issue

**Comment by andyblum** [comment] 2020-07-30 17:34
Thank you for your response.

**Comment by suyashkumar** [comment] 2020-08-14 18:08
Quick update on this: I've made some internal changes in [v0.5.4](https://github.com/google/fhir/releases/tag/v0.5.4) that update our import paths (to the familiar github.com prefixed go-gettable paths) and code location, the first step in making the library go-gettable and go mod compliant. 

The next step will be to generate and include the go proto code in the repo and have the go libraries depend directly on them (instead of relying on the bazel-based proto code generation), so that the go libraries will be go-gettable. :)

**Comment by loafoe** [comment] 2020-08-25 18:36
@suyashkumar running into the following:

main.go
```go
package main

import (
  _ "github.com/google/fhir/go/jsonformat"
)

func main() {
}
```

```
> go mod tidy
go: finding module for package github.com/google/fhir/go/jsonformat
go: downloading github.com/google/fhir v0.5.4
fhir imports
	github.com/google/fhir/go/jsonformat: create zip: module source tree too large (max size is 524288000 bytes)
```

Should we wait for .6 for Bazel-free usage?

Related Go ticket: https://github.com/golang/go/issues/40780

**Comment by suyashkumar** [comment] 2020-08-25 19:12
@loafoe We won't be able to fully support go modules until we generate and include the go proto code in the repo (as mentioned above, this is the next step). 

However, the repo size limitation you run into is interesting. I'm not super familiar with why our repo size is so large (@nickgeorge may know more): looking at the fhir-0.5.4.zip: https://github.com/google/fhir/archive/v0.5.4.zip (it seems like its around 111MB compressed, and ~900MB uncompressed). This may be a good reason to consider separating this library out from the rest of the FHIR repo if we will not be able to get around this limit, which will also be a blocker for adopting go modules.

**Comment by nickgeorge** [comment] 2020-08-25 19:17
hmm is the go module size just the size of the whole repo?  If it's just the go code, I'd be pretty surprised if it crossed some threashold.

As for the repo itself - my guess is most of that is the versions of the FHIR spec itself we have checked in, for use in proto generation.  I have a plan to run the proto generation off of MPM location as published by FHIR, at which point I'd likely expunge the checked-in versions of the spec from the git history.  That should result in a pretty significant drop in overall size.

**Comment by suyashkumar** [comment] 2020-08-25 19:26
Thanks @nickgeorge! Makes sense, it seems like the [checked in spec](https://github.com/google/fhir/tree/master/spec) is indeed ~700MB. Because go modules (and go get) rely on cloning the root repository to fetch and build the dependency, that's probably why it's running into an issue.  

One thing to note: while go modules may have this issue, `go get` does not seem to mind (however, as mentioned we need to check in the generated go protos before this will fully work without bazel).

**Comment by wesdean** [comment] 2020-10-15 14:32
Is there any way to generate the proto files ourselves and include them in a Go project so we can use the jsonformat package? If there is, are there instructions on how to do that?

**Comment by suyashkumar** [comment] 2020-10-15 22:00
Hi @wesdean! I wouldn't say this is recommended, but to answer your question: you can always use the [protocol buffer compiler `protoc`](https://github.com/protocolbuffers/protobuf/releases) with the [Go plugin](https://github.com/protocolbuffers/protobuf-go) to produce the generated Go proto code if you vendor this repository as a dependency in your repo. There would then be some work to reconcile the proto import paths in the `jsonformat` package with however you tell protoc to output the Go proto code as well.

Keep in mind that if you use Bazel as a build system for your project, you should not have to worry about any of this (Bazel will handle building the jsonformat package and building the required proto dependencies, though there are some setup costs with Bazel). 

In terms of where we are with `go mod` / `go get` support--there are various internal mechanics that need to be put into play to support the vendored go proto code reliably alongside internal tooling, which the team is working on putting in place for this issue among juggling other priorities. There is also likely another refactor needed to reduce the repo size to be workable with Go modules, which is part 2 of what needs to be done to have true Go modules support as discussed by Nick above.

**Comment by suyashkumar** [comment] 2020-12-03 03:33
Hi folks, with the release of [v0.7.0](https://github.com/google/fhir/releases/tag/v0.7.0), we have `go get` and go modules support alongside bazel support for the Go libraries 🎉. 

You can check out the updated [FHIR examples](https://github.com/google/fhir-examples/tree/master/go/google/fhir_examples) that now also use Go modules, and you can start using `github.com/google/fhir/go` as a Go module right away.

Let us know if you have any questions.

**Comment by nikklassen** [comment] 2020-12-03 14:35
Feel free to reopen if you encounter any issues

**Comment by wesdean** [comment] 2020-12-08 21:59
I am getting this error. Any ideas on how to resolve?
`go mod vendor`
`go: finding module for package github.com/google/fhir/go`
`github.com/anthem-ai/hos-adaptor-rest/internal/server imports`
`        github.com/google/fhir/go: module github.com/google/fhir/go@latest found (v0.0.0-20201203001644-a2580b6ea022), but does not contain package github.com/google/fhir/go`

**Comment by suyashkumar** [comment] 2020-12-08 22:16
Thanks for mentioning this! Can you give us a little more context on your setup? In particular your Go version, and if you're setting any environment variables (e.g. GOPROXY)? 

The easiest way to debug for us would be to try to set up a minimal repository that can reproduce this error and start from there. A minimal _working_ example with go modules can be seen [here](https://github.com/google/fhir-examples/tree/master/go/google/fhir_examples) (clone into your GOPATH, and you should be able to `go build` any of the Go binaries). 

Out of curiosity, does the minimal working example above work with your configuration (e.g. GOPROXY, etc?)

**Comment by suyashkumar** [comment] 2020-12-09 00:46
@wesdean I've also added a minimal working example (that doesn't require Synthea) [here](https://github.com/suyashkumar/fhir-test/runs/1521037136), and have also set it up with GitHub actions so you can have a small reproducible working playground if that's helpful

**Comment by wesdean** [comment] 2020-12-09 13:59
Thanks @suyashkumar. I solved it. I was trying to import
`"github.com/google/fhir/go"`
instead of
`"github.com/google/fhir/go/jsonformat"`

**Comment by suyashkumar** [comment] 2020-12-09 14:13
Great to hear! Let us know if you run into any other issues. Thanks!

**Comment by wesdean** [comment] 2020-12-09 16:29
Sorry to be a bother, but I'm having some trouble when serializing a Bundle. I'm getting an error on the Birth Date field of a Patient record.
`marshalMessageToMap repeated field entry: marshalRepeatedFieldValue entry[0]: marshalMessageToMap optional field resource: marshalMessageToMap optional field birth_date: serialize date: invalid timezone offset: America/Los_Angeles`
The Birth Date object looks like this.
`value_us:19700515 timezone:"America/Los_Angeles" precision:DAY`

When I set the Birth Date to nil, I get other serialization errors such as
`marshalMessageToMap repeated field entry: marshalRepeatedFieldValue entry[3]: marshalMessageToMap optional field resource: marshalMessageToMap optional field subject: invalid reference type *core.Reference`

**Comment by nikklassen** [comment] 2020-12-09 18:47
> marshalMessageToMap repeated field entry: marshalRepeatedFieldValue entry[0]: marshalMessageToMap optional field resource: marshalMessageToMap optional field birth_date: serialize date: invalid timezone offset: America/Los_Angeles
> The Birth Date object looks like this.
> value_us:19700515 timezone:"America/Los_Angeles" precision:DAY

FHIR proto timezones need to specified as an offset, i.e. "-08:00"

> marshalMessageToMap repeated field entry: marshalRepeatedFieldValue entry[3]: marshalMessageToMap optional field resource: marshalMessageToMap optional field subject: invalid reference type *core.Reference
> Could my issue have something to do with the bundle being from the hos-proto types?

We only support the Google FHIR protos in with this library. Some protos may happen to work by nature of reflection similarities, but this marshaller is specifically for our our protos.

**Comment by nikklassen** [comment] 2020-12-09 18:47
@wesdean Please open another issue is you have further questions and we'll be happy to help you there

**Closed by nikklassen** 2020-12-09 18:47 UTC
